apiVersion: v2
name: aws-load-balancer-controller
description: A Helm chart for Kubernetes
type: application
version: 1.3.3

dependencies:
  - name: aws-load-balancer-controller
    version: 1.3.3
    repository: https://aws.github.io/eks-charts 
  - name: aws-load-balancer-controller-crds
    version: 1.3.3
    repository: https://mthoretton.github.io/aws-load-balancer-controller-crds
