apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/applications.yaml
- base/ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.3/manifests/install.yaml

patchesStrategicMerge:
- overlays/service.yaml
- overlays/argocd-secret.yaml
- overlays/argocd-cm.yaml

patchesJson6902:
- path: overlays/deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

images:
- name: argoproj/argocd
  newTag: v1.8.3
- name: quay.io/argoproj/argocd
  newTag: v1.8.3
